title: w0xi
description: Memory forensics, network forensics, incident analysis.
remote_theme: jekyll/minima
permalink: /:title/
minima:
  skin: dark

header_pages:
  - about.md

show_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
